### ISSUE TITLE
Code block in Markdown

### ISSUE THREAD

**Issue by hanyihong0324** [Wamadahama/mahou-shoujo-syntax#1]
I'm using Markdown with Atom.
I think if a syntax can highlight the code blocks, or just set a different color from plain text, it will be a help.

**Comment by Wamadahama** [comment]
Working on it right now

**Comment by Wamadahama** [comment]
Just to clarify so I don't push the wrong thing, you are looking for something like this 

Before 
![2](https://cloud.githubusercontent.com/assets/7297073/16570683/91d09afc-4218-11e6-943c-806f5e4ee2f2.png)

After
![1](https://cloud.githubusercontent.com/assets/7297073/16570682/91ced686-4218-11e6-8622-415d040e44ee.png)

**Comment by hanyihong0324** [comment]
Oh, I don't know that I have to add the type of coding language after "```".
Thank you very much.
